apiVersion: doxchain.be-heroes/v1alpha1
kind: Node
metadata:
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/instance: node-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: node-sample
spec:
  # TODO(user): Add fields here
